engines:
  csslint:
    enabled: true
  duplication:
    enabled: enabled
    config:
      languages:
        javascript:
          mass_threshold: 50
  csslint:
    enabled: true
  eslint:
    enabled: true
    checks:
      max-statements:
        enabled: false
ratings:
  paths:
    - "src/**"
exclude_paths:
- "build/**/*"
